HCI-Restaurants/HCI-Restaurants/Models/Covid19.cs
using System;
using System.Collections.Generic;

namespace HCI_Restaurants.Models
{
    public partial class Covid19
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string TakeOut { get; set; }
        public string LimitSeating { get; set; }
        public string IndoorDining { get; set; }
        public string Curbside { get; set; }
        public string Comments { get; set; }

        public virtual Restaurants Restaurant { get; set; }
    }
}

HCI-Restaurants/HCI-Restaurants/Controllers/Covid19Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HCI_Restaurants.Models;

namespace HCI_Restaurants.Controllers
{
    public class Covid19Controller : Controller
    {
        private readonly hcirestaurantsContext _context;

        public Covid19Controller(hcirestaurantsContext context)
        {
            _context = context;
        }

        // GET: Covid19
        public async Task<IActionResult> Index()
        {
            var hcirestaurantsContext = _context.Covid19.Include(c => c.Restaurant);
            return View(await hcirestaurantsContext.ToListAsync());
        }

        // GET: Covid19/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var covid19 = await _context.Covid19
                .Include(c => c.Restaurant)
                .FirstOrDefaultAsync(m => m.RestaurantId == id);
            if (covid19 == null)
            {
                return NotFound();
            }

            return View(covid19);
        }

        // GET: Covid19/Create
        public IActionResult Create()
        {
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id");
            return View();
        }

        // POST: Covid19/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RestaurantId,TakeOut,LimitSeating,IndoorDining,Curbside,Comments")] Covid19 covid19)
        {
            if (ModelState.IsValid)
            {
                _context.Add(covid19);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id", covid19.RestaurantId);
            return View(covid19);
        }

        // GET: Covid19/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var covid19 = await _context.Covid19.FindAsync(id);
            if (covid19 == null)
            {
                return NotFound();
            }
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id", covid19.RestaurantId);
            return View(covid19);
        }

        // POST: Covid19/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,RestaurantId,TakeOut,LimitSeating,IndoorDining,Curbside,Comments")] Covid19 covid19)
        {
            if (id != covid19.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(covid19);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Covid19Exists(covid19.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id", covid19.RestaurantId);
            return View(covid19);
        }

        // GET: Covid19/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var covid19 = await _context.Covid19
                .Include(c => c.Restaurant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (covid19 == null)
            {
                return NotFound();
            }

            return View(covid19);
        }

        // POST: Covid19/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var covid19 = await _context.Covid19.FindAsync(id);
            _context.Covid19.Remove(covid19);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Covid19Exists(long id)
        {
            return _context.Covid19.Any(e => e.Id == id);
        }
    }
}

HCI-Restaurants/HCI-Restaurants/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HCI_Restaurants.Models;
using System.ComponentModel;

namespace HCI_Restaurants.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly hcirestaurantsContext _context;

        public RestaurantsController(hcirestaurantsContext context)
        {
            _context = context;
        }

        // GET: Restaurants
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "RestName" : "";
            ViewData["CuisineSortParm"] = string.IsNullOrEmpty(sortOrder) ? "CuisineType" : "";
            ViewData["DeliverySortParm"] = string.IsNullOrEmpty(sortOrder) ? "Delivery" : "";
            ViewData["TakeawaySortParm"] = string.IsNullOrEmpty(sortOrder) ? "Takeaway" : "";

            var rest = from r in _context.Restaurants
                       select r;
            if (!String.IsNullOrEmpty(searchString))
            {
                rest = rest.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "RestName":
                    rest = rest.OrderBy(r => r.Name);
                    break;
                case "CuisineType":
                    rest = rest.OrderBy(r => r.Cuisines);
                    break;
                case "Delivery":
                    rest = rest.OrderBy(r => r.HasDelivery);
                    break;
                case "Takeaway":
                    rest = rest.OrderBy(r => r.HasTakeaway);
                    break;
                default:
                    rest = rest.OrderBy(r => r.Id);
                    break;
            }

            //var hcirestaurantsContext = _context.Restaurants.Include(r => r.CityNavigation).Include(r => r.Cuisine);
            //return View(await hcirestaurantsContext.ToListAsync());

            return View(await rest.ToListAsync());
        }

        // GET: Restaurants/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants
                .Include(r => r.CityNavigation)
                .Include(r => r.Cuisine)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurants == null)
            {
                return NotFound();
            }

            return View(restaurants);
        }

        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id");
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id");
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CityId,CuisineId,Cuisines,Currency,Establishment,HasDelivery,HasTakeaway,Address,City,StateCode,Locality,LocalityVerbose,ZipCode,MenuUrl,Name,Telephone,PriceRange,Timings,Url,AggregateRating,RatingText")] Restaurants restaurants)
        {
            if (ModelState.IsValid)
            {
                _context.Add(restaurants);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", restaurants.CityId);
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id", restaurants.CuisineId);
            return View(restaurants);
        }

        // GET: Restaurants/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants.FindAsync(id);
            if (restaurants == null)
            {
                return NotFound();
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", restaurants.CityId);
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id", restaurants.CuisineId);
            return View(restaurants);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CityId,CuisineId,Cuisines,Currency,Establishment,HasDelivery,HasTakeaway,Address,City,StateCode,Locality,LocalityVerbose,ZipCode,MenuUrl,Name,Telephone,PriceRange,Timings,Url,AggregateRating,RatingText")] Restaurants restaurants)
        {
            if (id != restaurants.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurants);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantsExists(restaurants.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", restaurants.CityId);
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id", restaurants.CuisineId);
            return View(restaurants);
        }

        // GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants
                .Include(r => r.CityNavigation)
                .Include(r => r.Cuisine)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurants == null)
            {
                return NotFound();
            }

            return View(restaurants);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var restaurants = await _context.Restaurants.FindAsync(id);
            _context.Restaurants.Remove(restaurants);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantsExists(long id)
        {
            return _context.Restaurants.Any(e => e.Id == id);
        }
    }
}

HCI-Restaurants/HCI-Restaurants/Views/Covid19/Create.cshtml
@model HCI_Restaurants.Models.Covid19

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Covid19</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class ="form-control" asp-items="ViewBag.RestaurantId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TakeOut" class="control-label"></label>
                <input asp-for="TakeOut" class="form-control" />
                <span asp-validation-for="TakeOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LimitSeating" class="control-label"></label>
                <input asp-for="LimitSeating" class="form-control" />
                <span asp-validation-for="LimitSeating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IndoorDining" class="control-label"></label>
                <input asp-for="IndoorDining" class="form-control" />
                <span asp-validation-for="IndoorDining" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curbside" class="control-label"></label>
                <input asp-for="Curbside" class="form-control" />
                <span asp-validation-for="Curbside" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HCI-Restaurants/HCI-Restaurants/Views/Covid19/Delete.cshtml
@model HCI_Restaurants.Models.Covid19

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Covid19</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TakeOut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TakeOut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LimitSeating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LimitSeating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IndoorDining)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IndoorDining)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curbside)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curbside)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Restaurant.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HCI-Restaurants/HCI-Restaurants/Views/Covid19/Details.cshtml
@model HCI_Restaurants.Models.Covid19

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.Restaurant.Name</h1>

<div>
    <h4>Covid 19 Policy</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.TakeOut)*@
            Take Out
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TakeOut)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.LimitSeating)*@
            Limited Seating
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LimitSeating)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.IndoorDining)*@
            Indoor Dinning
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IndoorDining)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Curbside)*@
            Curbside Pickup
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curbside)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-controller="Restaurants" class="btn btn-primary">Back to Restaurants</a>
</div>

HCI-Restaurants/HCI-Restaurants/Views/Covid19/Edit.cshtml
@model HCI_Restaurants.Models.Covid19

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Covid19</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class="form-control" asp-items="ViewBag.RestaurantId"></select>
                <span asp-validation-for="RestaurantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TakeOut" class="control-label"></label>
                <input asp-for="TakeOut" class="form-control" />
                <span asp-validation-for="TakeOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LimitSeating" class="control-label"></label>
                <input asp-for="LimitSeating" class="form-control" />
                <span asp-validation-for="LimitSeating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IndoorDining" class="control-label"></label>
                <input asp-for="IndoorDining" class="form-control" />
                <span asp-validation-for="IndoorDining" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curbside" class="control-label"></label>
                <input asp-for="Curbside" class="form-control" />
                <span asp-validation-for="Curbside" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HCI-Restaurants/HCI-Restaurants/Views/Covid19/Index.cshtml
@model IEnumerable<HCI_Restaurants.Models.Covid19>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TakeOut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LimitSeating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IndoorDining)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curbside)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comments)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TakeOut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LimitSeating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IndoorDining)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Curbside)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comments)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>