HCI-Restaurants/HCI-Restaurants/Models/Restaurants.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace HCI_Restaurants.Models
{
    public partial class Restaurants
    {
        public Restaurants()
        {
            Covid19 = new HashSet<Covid19>();
            Reviews = new HashSet<Reviews>();
        }

        public int Id { get; set; }
        public int CityId { get; set; }
        public int CuisineId { get; set; }
        public string Cuisines { get; set; }
        public string Currency { get; set; }
        public string Establishment { get; set; }
        [DisplayName ("Delivery")]
        public string HasDelivery { get; set; }
        [DisplayName("Takeout")]
        public string HasTakeaway { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        [DisplayName("State Code")]
        public string StateCode { get; set; }
        public string Locality { get; set; }
        [DisplayName("Locality Verbose")]
        public string LocalityVerbose { get; set; }
        [DisplayName("Zip Code")]
        public string ZipCode { get; set; }
        [DisplayName("Menu")]
        public string MenuUrl { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        [DisplayName("Price Range")]
        public long? PriceRange { get; set; }
        [DisplayName("Hours")]
        public string Timings { get; set; }
        public string Url { get; set; }
        [DisplayName("Ratings")]
        public string AggregateRating { get; set; }
        [DisplayName("Comments")]
        public string RatingText { get; set; }

        public virtual Cities CityNavigation { get; set; }
        public virtual Cuisines Cuisine { get; set; }
        public virtual ICollection<Covid19> Covid19 { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}

HCI-Restaurants/HCI-Restaurants/Controllers/Covid19Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HCI_Restaurants.Models;

namespace HCI_Restaurants.Controllers
{
    public class Covid19Controller : Controller
    {
        private readonly hcirestaurantsContext _context;

        public Covid19Controller(hcirestaurantsContext context)
        {
            _context = context;
        }

        // GET: Covid19
        public async Task<IActionResult> Index()
        {
            var hcirestaurantsContext = _context.Covid19.Include(c => c.Restaurant);
            return View(await hcirestaurantsContext.ToListAsync());
        }

        // GET: Covid19/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var covid19 = await _context.Covid19
                .Include(c => c.Restaurant)
                .FirstOrDefaultAsync(m => m.RestaurantId == id);
            if (covid19 == null)
            {
                return NotFound();
            }

            return View(covid19);
        }

        // GET: Covid19/Create
        public IActionResult Create()
        {
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id");
            return View();
        }

        // POST: Covid19/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RestaurantId,TakeOut,LimitSeating,IndoorDining,Curbside,Comments")] Covid19 covid19)
        {
            if (ModelState.IsValid)
            {
                _context.Add(covid19);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id", covid19.RestaurantId);
            return View(covid19);
        }

        // GET: Covid19/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var covid19 = await _context.Covid19.FindAsync(id);
            if (covid19 == null)
            {
                return NotFound();
            }
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id", covid19.RestaurantId);
            return View(covid19);
        }

        // POST: Covid19/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,RestaurantId,TakeOut,LimitSeating,IndoorDining,Curbside,Comments")] Covid19 covid19)
        {
            if (id != covid19.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(covid19);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Covid19Exists(covid19.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "Id", "Id", covid19.RestaurantId);
            return View(covid19);
        }

        // GET: Covid19/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var covid19 = await _context.Covid19
                .Include(c => c.Restaurant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (covid19 == null)
            {
                return NotFound();
            }

            return View(covid19);
        }

        // POST: Covid19/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var covid19 = await _context.Covid19.FindAsync(id);
            _context.Covid19.Remove(covid19);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Covid19Exists(long id)
        {
            return _context.Covid19.Any(e => e.Id == id);
        }
    }
}

HCI-Restaurants/HCI-Restaurants/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HCI_Restaurants.Models;
using System.ComponentModel;

namespace HCI_Restaurants.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly hcirestaurantsContext _context;

        public RestaurantsController(hcirestaurantsContext context)
        {
            _context = context;
        }

        // GET: Restaurants
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "RestName" : "";
            ViewData["CuisineSortParm"] = string.IsNullOrEmpty(sortOrder) ? "CuisineType" : "";
            ViewData["DeliverySortParm"] = string.IsNullOrEmpty(sortOrder) ? "Delivery" : "";
            ViewData["TakeawaySortParm"] = string.IsNullOrEmpty(sortOrder) ? "Takeaway" : "";

            var rest = from r in _context.Restaurants
                       select r;
            if (!String.IsNullOrEmpty(searchString))
            {
                rest = rest.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "RestName":
                    rest = rest.OrderBy(r => r.Name);
                    break;
                case "CuisineType":
                    rest = rest.OrderBy(r => r.Cuisines);
                    break;
                case "Delivery":
                    rest = rest.OrderBy(r => r.HasDelivery);
                    break;
                case "Takeaway":
                    rest = rest.OrderBy(r => r.HasTakeaway);
                    break;
                default:
                    rest = rest.OrderBy(r => r.Id);
                    break;
            }

            //var hcirestaurantsContext = _context.Restaurants.Include(r => r.CityNavigation).Include(r => r.Cuisine);
            //return View(await hcirestaurantsContext.ToListAsync());

            return View(await rest.ToListAsync());
        }

        // GET: Restaurants/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants
                .Include(r => r.CityNavigation)
                .Include(r => r.Cuisine)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurants == null)
            {
                return NotFound();
            }

            return View(restaurants);
        }

        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id");
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id");
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CityId,CuisineId,Cuisines,Currency,Establishment,HasDelivery,HasTakeaway,Address,City,StateCode,Locality,LocalityVerbose,ZipCode,MenuUrl,Name,Telephone,PriceRange,Timings,Url,AggregateRating,RatingText")] Restaurants restaurants)
        {
            if (ModelState.IsValid)
            {
                _context.Add(restaurants);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", restaurants.CityId);
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id", restaurants.CuisineId);
            return View(restaurants);
        }

        // GET: Restaurants/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants.FindAsync(id);
            if (restaurants == null)
            {
                return NotFound();
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", restaurants.CityId);
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id", restaurants.CuisineId);
            return View(restaurants);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CityId,CuisineId,Cuisines,Currency,Establishment,HasDelivery,HasTakeaway,Address,City,StateCode,Locality,LocalityVerbose,ZipCode,MenuUrl,Name,Telephone,PriceRange,Timings,Url,AggregateRating,RatingText")] Restaurants restaurants)
        {
            if (id != restaurants.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurants);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantsExists(restaurants.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", restaurants.CityId);
            ViewData["CuisineId"] = new SelectList(_context.Cuisines, "Id", "Id", restaurants.CuisineId);
            return View(restaurants);
        }

        // GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants
                .Include(r => r.CityNavigation)
                .Include(r => r.Cuisine)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurants == null)
            {
                return NotFound();
            }

            return View(restaurants);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var restaurants = await _context.Restaurants.FindAsync(id);
            _context.Restaurants.Remove(restaurants);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantsExists(long id)
        {
            return _context.Restaurants.Any(e => e.Id == id);
        }
    }
}

HCI-Restaurants/HCI-Restaurants/Views/Restaurants/Create.cshtml
@model HCI_Restaurants.Models.Restaurants

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurants</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label"></label>
                <select asp-for="CityId" class ="form-control" asp-items="ViewBag.CityId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CuisineId" class="control-label"></label>
                <select asp-for="CuisineId" class ="form-control" asp-items="ViewBag.CuisineId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cuisines" class="control-label"></label>
                <input asp-for="Cuisines" class="form-control" />
                <span asp-validation-for="Cuisines" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label"></label>
                <input asp-for="Currency" class="form-control" />
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Establishment" class="control-label"></label>
                <input asp-for="Establishment" class="form-control" />
                <span asp-validation-for="Establishment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HasDelivery" class="control-label"></label>
                <input asp-for="HasDelivery" class="form-control" />
                <span asp-validation-for="HasDelivery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HasTakeaway" class="control-label"></label>
                <input asp-for="HasTakeaway" class="form-control" />
                <span asp-validation-for="HasTakeaway" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateCode" class="control-label"></label>
                <input asp-for="StateCode" class="form-control" />
                <span asp-validation-for="StateCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Locality" class="control-label"></label>
                <input asp-for="Locality" class="form-control" />
                <span asp-validation-for="Locality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityVerbose" class="control-label"></label>
                <input asp-for="LocalityVerbose" class="form-control" />
                <span asp-validation-for="LocalityVerbose" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuUrl" class="control-label"></label>
                <input asp-for="MenuUrl" class="form-control" />
                <span asp-validation-for="MenuUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceRange" class="control-label"></label>
                <input asp-for="PriceRange" class="form-control" />
                <span asp-validation-for="PriceRange" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Timings" class="control-label"></label>
                <input asp-for="Timings" class="form-control" />
                <span asp-validation-for="Timings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AggregateRating" class="control-label"></label>
                <input asp-for="AggregateRating" class="form-control" />
                <span asp-validation-for="AggregateRating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RatingText" class="control-label"></label>
                <input asp-for="RatingText" class="form-control" />
                <span asp-validation-for="RatingText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HCI-Restaurants/HCI-Restaurants/Views/Restaurants/Delete.cshtml
@model HCI_Restaurants.Models.Restaurants

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurants</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuisines)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuisines)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Establishment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Establishment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasDelivery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasDelivery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasTakeaway)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasTakeaway)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StateCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StateCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocalityVerbose)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocalityVerbose)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceRange)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceRange)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timings)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timings)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AggregateRating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AggregateRating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RatingText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RatingText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CityNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CityNavigation.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuisine.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HCI-Restaurants/HCI-Restaurants/Views/Restaurants/Details.cshtml
@model HCI_Restaurants.Models.Restaurants

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.Name</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Establishment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Establishment)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.HasDelivery)*@
            Delivery
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasDelivery)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.HasTakeaway)*@
            Take Away
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasTakeaway)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timings)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timings)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-primary">Back to Restaurants</a>
</div>

HCI-Restaurants/HCI-Restaurants/Views/Restaurants/Index.cshtml
@model IEnumerable<HCI_Restaurants.Models.Restaurants>

@{
    ViewData["Title"] = "The Restaurants Hub";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<h1>@ViewData["Title"]</h1>

<div class="container">
    <div class="dropdown" style="float:left; width:auto;">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
            Sort By
        </button>
        <ul class="dropdown-menu dropdown-content">
            <li>
                <a tabindex="-1" asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">Name A-Z</a>
            </li>
            <li>
                <a tabindex="-1" asp-action="Index" asp-route-sortOrder="@ViewData["CuisineSortParm"]">Cuisine Type</a>
            </li>
            <li class="dropdown-submenu">
                <a class="test btn-link dropdown-toggle" data-toggle="dropdown" href="#">Services<span class="caret"></span></a>
                <ul class="dropdown-menu dropdown-content">
                    <li>
                        <a tabindex="-1" asp-action="Index" asp-route-sortOrder="@ViewData["DeliverySortParm"]">Delivery</a>
                    </li>
                    <li>
                        <a tabindex="-1" asp-action="Index" asp-route-sortOrder="@ViewData["TakeawaySortParm"]">Takeaway</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <div style="float:right; width:auto; text-align:right">
        @using (Html.BeginForm())
        {
            <p>
                @Html.TextBox("SearchString")
                <input type="submit" value="Search" />
            </p>
        }
    </div>
</div>
<div class="text-break">
    <br />
    <br />
    <br />
</div>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {

            <div class="col-lg-6 mb-4">
                <div class="card" style="background-color: papayawhip">
                    <img class="card-img-top" src="" alt="" />
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.Cuisines)
                        </p>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.Address)
                        </p>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.City), @Html.DisplayFor(modelItem => item.StateCode) @Html.DisplayFor(modelItem => item.ZipCode)

                        </p>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.RatingText)
                        </p>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.Telephone)
                        </p>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.Reviews)
                        </p>

                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a> |
                        <a asp-action="Details" asp-controller="Covid19" asp-route-id="@item.Id" class="btn btn-dark">Delivery</a> 
                        <a asp-action="Index" asp-controller="Reviews" asp-route-id="@item.Id" class="btn btn-success float-right">Reviews</a>
                    </div>
                </div>
            </div>

        }
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.dropdown-submenu a.test').on("click", function (e) {
            $(this).next('ul').toggle();
            e.stopPropagation();
            e.preventDefault();
        });
    });
</script>

<style>
    .dropdown-submenu {
        position: relative;
    }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        /*overflow: auto;*/ /*Removed for better visualization*/
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

    .dropdown a:hover {
        background-color: #ddd;
    }
</style>